version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: uvicorn main:app --host '0.0.0.0' --port 8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: "node:14-alpine"
    user: "node"
    volumes:
      - ./frontend:/frontend
    command: "yarn start"
    ports:
      - "9999:9999"
    depends_on:
      - backend
