AUDIO_OUTPUT_DIR = "./audio"
AUDIO_FILE_1s = "./audio/whitenoise_1s.wav"
AUDIO_FILE_60s = "./audio/whitenoise_60s.wav"
AUDIO_FILE_25m = "./audio/whitenoise_1500s.wav"
AUDIO_FILE_30m = "./audio/whitenoise_1800s.wav"
